Meat_Order_App/calculator/views.py
from flask import Blueprint, render_template, redirect, url_for, session, flash
from Meat_Order_App.calculator.forms import PoundForm, ItemOneForm, ItemTwoForm, ItemThreeForm, ItemFourForm, \
                                            ItemFiveForm, ItemSixForm, ItemSevenForm, OrderReview, OrderSummary
from Meat_Order_App.calculator.api_call import *

# These link the blueprints from this python file to the __init__ file
# That allow the flask_app.py to call the routes
pounds_blueprint = Blueprint('total_pounds', __name__, template_folder='templates/calculator')
item1_info_blueprint = Blueprint('item1_pounds', __name__, template_folder='templates/calculator')
item2_info_blueprint = Blueprint('item2_pounds', __name__, template_folder='templates/calculator')
item3_info_blueprint = Blueprint('item3_pounds', __name__, template_folder='templates/calculator')
item4_info_blueprint = Blueprint('item4_pounds', __name__, template_folder='templates/calculator')
item5_info_blueprint = Blueprint('item5_pounds', __name__, template_folder='templates/calculator')
item6_info_blueprint = Blueprint('item6_pounds', __name__, template_folder='templates/calculator')
item7_info_blueprint = Blueprint('item7_pounds', __name__, template_folder='templates/calculator')
item_review_blueprint = Blueprint('item_delete', __name__, template_folder='templates/calculator')
order_summary_blueprint = Blueprint('order_summary', __name__, template_folder='templates/calculator')

# This is the list that stores the items
cart_list = []
item1_dict = {}
item2_dict = {}
item3_dict = {}
item4_dict = {}
item5_dict = {}
item6_dict = {}
item7_dict = {}


# This is the route for the form that identifies the total pounds of meat you have
@pounds_blueprint.route('/basic_info', methods=['GET', 'POST'])
def total_pounds():
    form = PoundForm()

    if form.validate_on_submit():
        session['remaining_pounds'] = round(form.total_pounds.data)
        session['total_price'] = 0
        return render_template('item_list.html')

    return render_template('basic_info.html', form=form)


# This is the route for the first item in the list
# This asks for a form of how many pounds you would like to order for the item
@item1_info_blueprint.route('/item1_info', methods=['GET', 'POST'])
def item1_info():
    form = ItemOneForm()

    if form.validate_on_submit():
        session['item1_pounds'] = form.item1_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item1_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item1_pounds']
            session['item1_price'] = items_list[2]['price'] * session['item1_pounds']
            session['total_price'] = session['total_price'] + session['item1_price']
            cart_list.append(items_list[2]['item_name'])
            item1_dict['name'] = items_list[2]['item_name']
            item1_dict['pounds'] = session['item1_pounds']
            item1_dict['price'] = session['item1_price']
            return render_template('item_list.html')

    return render_template('item1_info.html', form=form, item1_name=items_list[2]['item_name'],
                           item1_price=round(float(items_list[2]['price']), 2))


# This is the route for the second item in the list
# This asks for a form of how many pounds you would like to order for the item
@item2_info_blueprint.route('/item2_info', methods=['GET', 'POST'])
def item2_info():
    form = ItemTwoForm()

    if form.validate_on_submit():
        session['item2_pounds'] = form.item2_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item2_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
            # print(session['total_price'])
            # print(session['remaining_pounds'])
            # print(cart_list)
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item2_pounds']
            session['item2_price'] = items_list[3]['price'] * session['item2_pounds']
            session['total_price'] = session['total_price'] + session['item2_price']
            cart_list.append(items_list[3]['item_name'])
            item2_dict['name'] = items_list[3]['item_name']
            item2_dict['pounds'] = session['item2_pounds']
            item2_dict['price'] = session['item2_price']
            return render_template('item_list.html')

    return render_template('item2_info.html', form=form, item2_name=items_list[3]['item_name'],
                           item2_price=round(float(items_list[3]['price']), 2))


# This is the route for the third item in the list
# This asks for a form of how many pounds you would like to order for the item
@item3_info_blueprint.route('/item3_info', methods=['GET', 'POST'])
def item3_info():
    form = ItemThreeForm()

    if form.validate_on_submit():
        session['item3_pounds'] = form.item3_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item3_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
            # print(session['total_price'])
            # print(session['remaining_pounds'])
            # print(cart_list)
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item3_pounds']
            session['item3_price'] = items_list[6]['price'] * session['item3_pounds']
            session['total_price'] = session['total_price'] + session['item3_price']
            cart_list.append(items_list[6]['item_name'])
            item3_dict['name'] = items_list[6]['item_name']
            item3_dict['pounds'] = session['item3_pounds']
            item3_dict['price'] = session['item3_price']
            return render_template('item_list.html')

    return render_template('item3_info.html', form=form, item3_name=items_list[6]['item_name'],
                           item3_price=round(float(items_list[6]['price']), 2))


@item4_info_blueprint.route('/item4_info', methods=['GET', 'POST'])
def item4_info():
    form = ItemFourForm()

    if form.validate_on_submit():
        session['item4_pounds'] = form.item4_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item4_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item4_pounds']
            session['item4_price'] = items_list[4]['price'] * session['item4_pounds']
            session['total_price'] = session['total_price'] + session['item4_price']
            cart_list.append(items_list[4]['item_name'])
            item4_dict['name'] = items_list[4]['item_name']
            item4_dict['pounds'] = session['item4_pounds']
            item4_dict['price'] = session['item4_price']
            return render_template('item_list.html')

    return render_template('item4_info.html', form=form, item4_name=items_list[4]['item_name'],
                           item4_price=round(float(items_list[4]['price']), 2))


@item5_info_blueprint.route('/item5_info', methods=['GET', 'POST'])
def item5_info():
    form = ItemFiveForm()

    if form.validate_on_submit():
        session['item5_pounds'] = form.item5_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item5_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item5_pounds']
            session['item5_price'] = items_list[0]['price'] * session['item5_pounds']
            session['total_price'] = session['total_price'] + session['item5_price']
            cart_list.append(items_list[0]['item_name'])
            item5_dict['name'] = items_list[0]['item_name']
            item5_dict['pounds'] = session['item5_pounds']
            item5_dict['price'] = session['item5_price']
            return render_template('item_list.html')

    return render_template('item5_info.html', form=form, item5_name=items_list[0]['item_name'],
                           item5_price=round(float(items_list[0]['price']), 2))


@item6_info_blueprint.route('/item6_info', methods=['GET', 'POST'])
def item6_info():

Meat_Order_App/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Malafys</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('homepage')}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{{url_for('total_pounds.total_pounds')}}">Order Info</a>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('products')}}">Item List</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{{url_for('item_delete.order_review')}}">Order Review</a>
      </li>
    </ul>
  </div>
</nav>
    {% block content %}

    {% endblock %}
</body>
</html>

Meat_Order_App/templates/homepage.html
{% extends "base.html" %}
{% block content %}
<style>
    #instructions {
        margin-right: 30px;
        margin-left: 30px;
              }
    #hd1 {
        text-decoration: underline;
    }
</style>
<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h1 style="text-decoration: underline;">Malafy's Meat Processing LLC</h1>
    <p>Welcome to the homepapge. Here you can access the calculations for your meat order by pressing the button below.</p>
    <a href="http://www.malafysmeatprocessing.com/" class="link">Malafays Website</a>
    <hr>
    <a href="{{url_for('total_pounds.total_pounds')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Begin Order</a>
</div>
<div id="instructions">
    <h5>This website is designed to do all the hard work of calculating your order of meat for Malafays</h5>
    <br>
    <h6 id="hd1">Instructions follow as below:</h6>
    <ol>
        <li>Click to Begin Order</li>
        <li>Enter the amount of pounds you venison you have</li>
        <li>Click the item you would like to add, and enter the amount of that item you would like</li>
        <li>Once you finish adding the items click item review at the bottom of the item list page</li>
        <li>The Order Review page will give you directions on any last minute changes</li>
        <li>Once you click submit on Order Review, you will be given a summary of your order</li>
        <li>The order summary includes Total Price, Price per item and pounds per item</li>
        <li>After your finished you can reset if you want to complete another order</li>
    </ol>
</div>

{% endblock %}