Meat_Order_App/calculator/views.py
from flask import Blueprint, render_template, redirect, url_for, session, flash
from Meat_Order_App.calculator.forms import PoundForm, ItemOneForm, ItemTwoForm, ItemThreeForm, ItemFourForm, \
                                            ItemFiveForm, ItemSixForm, ItemSevenForm, OrderReview, OrderSummary
from Meat_Order_App.calculator.api_call import *

# These link the blueprints from this python file to the __init__ file
# That allow the flask_app.py to call the routes
pounds_blueprint = Blueprint('total_pounds', __name__, template_folder='templates/calculator')
item1_info_blueprint = Blueprint('item1_pounds', __name__, template_folder='templates/calculator')
item2_info_blueprint = Blueprint('item2_pounds', __name__, template_folder='templates/calculator')
item3_info_blueprint = Blueprint('item3_pounds', __name__, template_folder='templates/calculator')
item4_info_blueprint = Blueprint('item4_pounds', __name__, template_folder='templates/calculator')
item5_info_blueprint = Blueprint('item5_pounds', __name__, template_folder='templates/calculator')
item6_info_blueprint = Blueprint('item6_pounds', __name__, template_folder='templates/calculator')
item7_info_blueprint = Blueprint('item7_pounds', __name__, template_folder='templates/calculator')
item_review_blueprint = Blueprint('item_delete', __name__, template_folder='templates/calculator')
order_summary_blueprint = Blueprint('order_summary', __name__, template_folder='templates/calculator')

# This is the list that stores the items
cart_list = []
item1_dict = {}
item2_dict = {}
item3_dict = {}
item4_dict = {}
item5_dict = {}
item6_dict = {}
item7_dict = {}


# This is the route for the form that identifies the total pounds of meat you have
@pounds_blueprint.route('/basic_info', methods=['GET', 'POST'])
def total_pounds():
    form = PoundForm()

    if form.validate_on_submit():
        session['remaining_pounds'] = round(form.total_pounds.data)
        session['total_price'] = 0
        return render_template('item_list.html')

    return render_template('basic_info.html', form=form)


# This is the route for the first item in the list
# This asks for a form of how many pounds you would like to order for the item
@item1_info_blueprint.route('/item1_info', methods=['GET', 'POST'])
def item1_info():
    form = ItemOneForm()

    if form.validate_on_submit():
        session['item1_pounds'] = form.item1_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item1_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item1_pounds']
            session['item1_price'] = items_list[2]['price'] * session['item1_pounds']
            session['total_price'] = session['total_price'] + session['item1_price']
            cart_list.append(items_list[2]['item_name'])
            item1_dict['name'] = items_list[2]['item_name']
            item1_dict['pounds'] = session['item1_pounds']
            item1_dict['price'] = session['item1_price']
            return render_template('item_list.html')

    return render_template('item1_info.html', form=form, item1_name=items_list[2]['item_name'],
                           item1_price=round(float(items_list[2]['price']), 2))


# This is the route for the second item in the list
# This asks for a form of how many pounds you would like to order for the item
@item2_info_blueprint.route('/item2_info', methods=['GET', 'POST'])
def item2_info():
    form = ItemTwoForm()

    if form.validate_on_submit():
        session['item2_pounds'] = form.item2_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item2_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
            # print(session['total_price'])
            # print(session['remaining_pounds'])
            # print(cart_list)
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item2_pounds']
            session['item2_price'] = items_list[3]['price'] * session['item2_pounds']
            session['total_price'] = session['total_price'] + session['item2_price']
            cart_list.append(items_list[3]['item_name'])
            item2_dict['name'] = items_list[3]['item_name']
            item2_dict['pounds'] = session['item2_pounds']
            item2_dict['price'] = session['item2_price']
            return render_template('item_list.html')

    return render_template('item2_info.html', form=form, item2_name=items_list[3]['item_name'],
                           item2_price=round(float(items_list[3]['price']), 2))


# This is the route for the third item in the list
# This asks for a form of how many pounds you would like to order for the item
@item3_info_blueprint.route('/item3_info', methods=['GET', 'POST'])
def item3_info():
    form = ItemThreeForm()

    if form.validate_on_submit():
        session['item3_pounds'] = form.item3_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item3_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
            # print(session['total_price'])
            # print(session['remaining_pounds'])
            # print(cart_list)
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item3_pounds']
            session['item3_price'] = items_list[6]['price'] * session['item3_pounds']
            session['total_price'] = session['total_price'] + session['item3_price']
            cart_list.append(items_list[6]['item_name'])
            item3_dict['name'] = items_list[6]['item_name']
            item3_dict['pounds'] = session['item3_pounds']
            item3_dict['price'] = session['item3_price']
            return render_template('item_list.html')

    return render_template('item3_info.html', form=form, item3_name=items_list[6]['item_name'],
                           item3_price=round(float(items_list[6]['price']), 2))


@item4_info_blueprint.route('/item4_info', methods=['GET', 'POST'])
def item4_info():
    form = ItemFourForm()

    if form.validate_on_submit():
        session['item4_pounds'] = form.item4_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item4_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item4_pounds']
            session['item4_price'] = items_list[4]['price'] * session['item4_pounds']
            session['total_price'] = session['total_price'] + session['item4_price']
            cart_list.append(items_list[4]['item_name'])
            item4_dict['name'] = items_list[4]['item_name']
            item4_dict['pounds'] = session['item4_pounds']
            item4_dict['price'] = session['item4_price']
            return render_template('item_list.html')

    return render_template('item4_info.html', form=form, item4_name=items_list[4]['item_name'],
                           item4_price=round(float(items_list[4]['price']), 2))


@item5_info_blueprint.route('/item5_info', methods=['GET', 'POST'])
def item5_info():
    form = ItemFiveForm()

    if form.validate_on_submit():
        session['item5_pounds'] = form.item5_pounds.data

        # This if-else statement checks to see if you have enough meat to order your requested amount
        # The if clause checks if the remaining meat is less than the meat asked for
        # if it holds true the user cannot continue with the order
        # if the user has enough it continues on with the form
        if session['remaining_pounds'] < session['item5_pounds']:
            flash('Sorry, you cannot complete this item order. You do not have enough meat remaining.')
        else:
            session['remaining_pounds'] = session['remaining_pounds'] - session['item5_pounds']
            session['item5_price'] = items_list[0]['price'] * session['item5_pounds']
            session['total_price'] = session['total_price'] + session['item5_price']
            cart_list.append(items_list[0]['item_name'])
            item5_dict['name'] = items_list[0]['item_name']
            item5_dict['pounds'] = session['item5_pounds']
            item5_dict['price'] = session['item5_price']
            return render_template('item_list.html')

    return render_template('item5_info.html', form=form, item5_name=items_list[0]['item_name'],
                           item5_price=round(float(items_list[0]['price']), 2))


@item6_info_blueprint.route('/item6_info', methods=['GET', 'POST'])
def item6_info():

Meat_Order_App/calculator/templates/calculator/basic_info.html
{% extends "base.html" %}
{% block content %}

{# This is the template that asks for the basic info on your order. #}
<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h3 style="text-decoration:underline;">Malafy's Meat Processing LLC</h3>
    <p style="margin:0px;padding:0px;">In order to help you identify the cost distribution of your meat</p>
    <p style="margin:0px;padding:0px;"> Please provide the amount of meat you have in the form below.</p>
    <p style="color:rgb(165, 28, 28)">Note: If your amount is not rounded, it will automatically round to the nearest whole number.</p>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{form.total_pounds.label}}{{form.total_pounds()}}
        {{form.submit()}}
    </form>
</div>
{% endblock %}

Meat_Order_App/calculator/templates/calculator/item1_info.html
{% extends "base.html" %}
{% block content %}

    {# This block of code below pops up a message saying that you do not have enough meat left #}
    {% for mess in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Not enough Meat!</h4>
            {{mess}}
            <p> you only have {{session['remaining_pounds']}} pounds of meat left.</p>
    {% endfor %}
        </div>

<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h2>{{item1_name}}</h2>
    <h5>Price (per pound): ${{item1_price}}0</h5>
    <p style="margin-bottom:0px;padding-bottom;">Purchases must be made in sets of 5 pounds</p>
    <br>
    <form method="POST" style="margin:0px;padding:0px;">
        {{ form.hidden_tag() }}
        {{form.item1_pounds.label}}{{form.item1_pounds()}}
        {{form.submit()}}
    </form>
</div>
<div>
    <a style="margin-left:30px" href="{{url_for('products')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Return Item List</a>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/item2_info.html
{% extends "base.html" %}
{% block content %}

{# This block of code below pops up a message saying that you do not have enough meat left #}
    {% for mess in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Not enough Meat!</h4>
            {{mess}}
            <p> you only have {{session['remaining_pounds']}} pounds of meat left.</p>
    {% endfor %}
        </div>
<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h1>{{item2_name}}</h1>
    <h3>Price (per pound): ${{item2_price}}0</h3>
    <p>Purchases must be made in sets of 5 pounds</p>
    <br>
    <form method='POST' >
        {{ form.hidden_tag() }}
        {{form.item2_pounds.label}}{{form.item2_pounds()}}
        {{form.submit()}}
    </form>
</div>
<div>
    <a style="margin-left:30px" href="{{url_for('products')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Return Item List</a>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/item3_info.html
{% extends "base.html" %}
{% block content %}

{# This block of code below pops up a message saying that you do not have enough meat left #}
    {% for mess in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Not enough Meat!</h4>
            {{mess}}
            <p> you only have {{session['remaining_pounds']}} pounds of meat left.</p>
    {% endfor %}
        </div>
<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h1>{{item3_name}}</h1>
    <h3>Price (per pound): ${{item3_price}}0</h3>
    <p>Purchases must be made in sets of 5 pounds</p>
    <br>
    <form method='POST'>
        {{ form.hidden_tag() }}
        {{form.item3_pounds.label}}
        {{form.item3_pounds()}}
        {{form.submit()}}
    </form>
</div>
<div>
    {# button to return to item list and cancel order in progress #}
    <a style="margin-left:30px" href="{{url_for('products')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Return Item List</a>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/item4_info.html
{% extends "base.html" %}
{% block content %}

    {# This block of code below pops up a message saying that you do not have enough meat left #}
    {% for mess in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Not enough Meat!</h4>
            {{mess}}
            <p> you only have {{session['remaining_pounds']}} pounds of meat left.</p>
        <hr>
    {% endfor %}
        </div>

<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h1>{{item4_name}}</h1>
    <h3>Price (per pound): ${{item4_price}}0</h3>
    <p>Purchases must be made in sets of 5 pounds</p>
    <br>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{form.item4_pounds.label}}{{form.item4_pounds()}}
        {{form.submit()}}
    </form>
</div>
<div>
    <a style="margin-left:30px" href="{{url_for('products')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Return Item List</a>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/item5_info.html
{% extends "base.html" %}
{% block content %}

    {# This block of code below pops up a message saying that you do not have enough meat left #}
    {% for mess in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Not enough Meat!</h4>
            {{mess}}
            <p> you only have {{session['remaining_pounds']}} pounds of meat left.</p>
    {% endfor %}
        </div>

<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h1>{{item5_name}}</h1>
    <h3>Price (per pound): ${{item5_price}}0</h3>
    <p>Purchases must be made in sets of 5 pounds</p>
    <br>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{form.item5_pounds.label}}{{form.item5_pounds()}}
        {{form.submit()}}
    </form>
</div>
<div>
    <a style="margin-left:30px" href="{{url_for('products')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Return Item List</a>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/item6_info.html
{% extends "base.html" %}
{% block content %}

    {# This block of code below pops up a message saying that you do not have enough meat left #}
    {% for mess in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Not enough Meat!</h4>
            {{mess}}
            <p> you only have {{session['remaining_pounds']}} pounds of meat left.</p>
    {% endfor %}
        </div>

<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h1>{{item6_name}}</h1>
    <h3>Price (per pound): ${{item6_price}}0</h3>
    <p>Purchases must be made in sets of 5 pounds</p>
    <br>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{form.item6_pounds.label}}{{form.item6_pounds()}}
        {{form.submit()}}
    </form>
</div>
<div>
    <a style="margin-left:30px" href="{{url_for('products')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Return Item List</a>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/item7_info.html
{% extends "base.html" %}
{% block content %}

    {# This block of code below pops up a message saying that you do not have enough meat left #}
    {% for mess in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Not enough Meat!</h4>
            {{mess}}
            <p> you only have {{session['remaining_pounds']}} pounds of meat left.</p>
    {% endfor %}
        </div>

<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h1>{{item7_name}}</h1>
    <h3>Price (per pound): ${{item7_price}}0</h3>
    <p>Purchases must be made in sets of 5 pounds</p>
    <br>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{form.item7_pounds.label}}{{form.item7_pounds()}}
        {{form.submit()}}
    </form>
</div>
<div>
    <a style="margin-left:30px" href="{{url_for('products')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Return Item List</a>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/item_list.html
{% extends "base.html" %}
{% block content %}

{# This is the template that displays the item list#}
<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h3 style="text-decoration:underline;">Malafy's Meat Processing LLC</h3>
    <h4>Product Items:</h4>
    <p style="margin:0px;padding:0px;">Below is a list of the items you may purchase.</p>
    <p style="margin:0px;padding:0px;">Please click the link of the item you would like to buy.</p>
    <p style="margin:0px;padding:0px;"> When you are finished, please click Review Order.</p>
</div>
<div class="list-group" style="margin:10px;">
    <a href="{{url_for('item1_pounds.item1_info')}}" class="list-group-item list-group-item-action">Venison Ground with Added Fat</a>
    <a href="{{url_for('item2_pounds.item2_info')}}" class="list-group-item list-group-item-action">Venison Breakfast Sausage (Bulk)</a>
    <a href="{{url_for('item3_pounds.item3_info')}}" class="list-group-item list-group-item-action">Venison Sweet Sausage (Bulk)</a>
    <a href="{{url_for('item4_pounds.item4_info')}}" class="list-group-item list-group-item-action">Venison Hot Sausage (Bulk)</a>
    <a href="{{url_for('item5_pounds.item5_info')}}" class="list-group-item list-group-item-action">Venison Breakfast Sausage (Link)</a>
    <a href="{{url_for('item6_pounds.item6_info')}}" class="list-group-item list-group-item-action">Venison Sweet Sausage (Link)</a>
    <a href="{{url_for('item7_pounds.item7_info')}}" class="list-group-item list-group-item-action">Venison Hot Sausage (Link)</a>
</div>
<div>
    <a style="margin:10px;" href="{{url_for('item_delete.order_review')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Review Order</a>
</div>
{% endblock %}

Meat_Order_App/calculator/templates/calculator/order_review.html
{% extends "base.html" %}
{% block content %}

{#This is the template that shows the order review#}
<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h3 style="text-decoration:underline;">Malafy's Meat Processing LLC</h3>
    <h4>Order Review:</h4>
    <p style="margin:0px;padding:0px;">Below you will see a list of the items you ordered.</p>
    <p style="margin:0px;padding:0px;">Press continue if you would like to see the order summary.</p>
    <p style="margin:0px;padding:0px;">Type in the item name if you would like to remove it.</p>
    <p style="margin:0px;padding:0px;">Or type Cancel in the input box to discard you order.</p>
    <p style="margin:0px;padding:0px;color:rgb(165, 28, 28)">PLEASE NOTE: Choosing 'cancel' will discard your entire order! </p>
</div>
<div>
{% for item in cart_list %}
    <h4 style="margin-left:30px">Item Name: {{item}}</h4>
    <br>
{% endfor %}
    <form method='POST' style="margin-left:30px;marign-top:0px;">
        {{ form.hidden_tag() }}
        {{form.item_delete.label}}
        {{form.item_delete()}}
        {{form.submit()}}
    </form>
    <a style="margin-left:30px" href="{{url_for('item_delete.order_review')}}" class="btn btn-outline-secondary active" role="button" aria-pressed="true" data-toggle="modal" data-target="#confirm_order">Order Summary</a>
</div>
<div class="modal" tabindex="-1" role="dialog" id="confirm_order">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you are finished with your order?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Not Yet</button>
        <a  href="{{url_for('order_summary.summary')}}" class="btn btn-success active" role="button" aria-pressed="true">Yes, Continue</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Meat_Order_App/calculator/templates/calculator/order_summary.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron" style="padding-top:30px;padding-bottom:30px;">
    <h3 style="text-decoration:underline;">Malafy's Meat Processing LLC</h3>
    <h4 style="margin-bottom:0px;padding-bottom:0px;">Order Summary:</h4>
    <p style="margin-top:5px;padding-top:0px;">Below is all the information regarding your order</p>
    <p style="font-weight:bold;"> Total Price: ${{total_price}}</p>
    <p style="font-weight:bold"> Meat Remaining: {{remaining_pounds}} lbs</p>
</div>
<div style="margin-left:30px;padding-top:0px;">
   <h3 style="text-decoration:underline;">Item List:</h3>
    {% for key, values in item1_dict.items() %}
    <ul style="margin:0px;padding:0px;">
       <li>Item {{key}}: {{values}}</li>
    </ul>
    {% endfor %}
    <br>
    {% for key, values in item2_dict.items() %}
    <ul>
       <li>Item {{key}}: {{values}}</li>
    </ul>
    {% endfor %}
    {% for key, values in item3_dict.items() %}
    <ul>
       <li>Item {{key}}: {{values}}</li>
    </ul>
    {% endfor %}
    {% for key, values in item4_dict.items() %}
    <ul>
       <li>Item {{key}}: {{values}}</li>
    </ul>
    {% endfor %}
    {% for key, values in item5_dict.items() %}
    <ul>
       <li>Item {{key}}: {{values}}</li>
    </ul>
    {% endfor %}
    {% for key, values in item6_dict.items() %}
    <ul>
       <li>Item {{key}}: {{values}}</li>
    </ul>
    {% endfor %}
    {% for key, values in item7_dict.items() %}
    <ul>
       <li>Item {{key}}: {{values}}</li>
    </ul>
    {% endfor %}
</div>
<div>
    <form method="POST" style="margin-left:30px;padding:0px;">
        {{ form.hidden_tag() }}
        <p>If you would like to start over press the button.</p>
        {{form.submit()}}
    </form>
</div>

{% endblock %}